version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 14
pre-build:
  commands:
    - echo installing dependancies
    - sudo npm install -g @angular/cli
build:
  commands:
    - npm install
artifacts:
  files:
    - '**/*'
